import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter as FontSans, Inter } from 'next/font/google';
import localFont from 'next/font/local';
import '@/styles/globals.css';
import '@/styles/mdx.css';
import '@/styles/editor.css';
import { ThemeProvider } from '@/components/theme-provider';
import MainNav from '@/components/mainNav';

const inter = Inter({ subsets: ['latin'] });

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        suppressHydrationWarning={true}
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontHeading.variable,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <MainNav />
          <div className="w-full flex justify-center ">
            <div className="max-w-[1336px] w-full relative">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
